# Generated by Django 2.1.7 on 2019-03-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='avatar',
        ),
    ]
