# Generated by Django 2.1.7 on 2019-03-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_shopuser_send_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='send_mode',
            field=models.BooleanField(default=False),
        ),
    ]
